### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by marcosmilzo** [hemberg-lab/D3E#3]
To be deleted

**Comment by mhemberg** [comment]
Hi Marco,

thank you very much for reporting this issue. We have not encountered it 
in our testing and we would very much appreciate if you fixed this since 
I suppose that it is a matter of changing the int() to float(). Please 
let me know what course of action you take.

Best Regards,

Martin

On 09/12/15 09:37, Marco wrote:

> Hello,
> 
> I've been testing D3E, and I have to admit that all the time I am 
> testing the t3 option (Likelihood ratio test) I am encountering the 
> following problem:
> 
> File "~/bin/D3E/D3EUtil.py", line 444, in logLikelihood
> gamma = int(round(params.gamma))+1
> ValueError: cannot convert float NaN to integer
> 
> I do think this is a python problem, it cannot handle NaN as integer, 
> but just as floating.
> Should I update something or did you face the same problem?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/hemberg-lab/D3E/issues/3.

## 

Martin Hemberg

Career Development Fellow Group Leader
Computational Genomics Programme
Wellcome Trust Sanger Institute
Wellcome Trust Genome Campus
Hinxton
Cambridge, CB10 1SA

Tel: +44(0)1223499955

http://www.sanger.ac.uk/science/groups/hemberg-group

martin.hemberg@sanger.ac.uk

## 

 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
